name: pipeline
on: push

jobs:
  scan:
    name: scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: check formatting
      run: cargo fmt --all -- --check
    # - name: scan code
    #   run: |
    #     rustup component add clippy
    #     cargo clippy --all-targets --all-features -- -D warnings
  test:
    name: test (${{ matrix.name }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: "default"
          features: ""
    steps:
    - uses: actions/checkout@v1
    - name: install toolchain
      run: rustup default stable
    - name: install tools
      run: sudo apt-get install build-essential
    - name: execute unit tests
      run: cargo test ${{ matrix.features }}
  build:
    name: build (${{ matrix.name }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: "default"
          features: ""
    steps:
    - uses: actions/checkout@v1
    - name: install toolchain
      run: rustup default stable
    - name: install tools
      run: sudo apt-get install build-essential
    - name: build program
      run: cargo build --release --locked ${{ matrix.features }}
